# Generated by Django 5.0.6 on 2024-06-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='emergency_contact',
            new_name='emergency_contact_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='emergency_contact_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
