# Generated by Django 5.0.6 on 2024-06-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_rename_emergency_contact_reservation_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
