# Generated by Django 5.0.6 on 2024-06-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0005_alter_car_make_alter_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='company_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
