# Generated by Django 5.0.6 on 2024-06-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0006_reservation_company_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
