# Generated by Django 5.0.6 on 2024-06-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0007_reservation_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reference_number',
            field=models.CharField(blank=True, default='TEMP', max_length=20),
        ),
    ]
