# Generated by Django 5.0.6 on 2024-07-08 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0010_car_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='showroom.car'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
