# Generated by Django 5.0.6 on 2024-06-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
